### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by gabrc52** [sipb/class_group_chats#1]
MVP (before fall 2023):

- [x] Add contact info in the footer
- [x] You can search classes by exact course number
- [x] You can see how many people are in a group chat
- [x] You can hit ~~"Create and join" or "Join"~~ "Invite me" to receive an invite
- [x] Make it functional, without asking for authentication or simply putting a kerb text box temporarily

Improvements (before fall 2023)
- [ ] Add some authentication
- [x] ~~Make room semi-unfederated from our plug-in (nvm invite rule is already invite huh yeah I don't know why I thought that was needed)~~ Ensure only students can join the chats (maybe make a custom endpoint for affiliation) - this is done from the endpoint or web app and not 

The problem is we'd need to query LDAP since the people API isn't complete. But we already have the affiliation from SAML so we can (1) enable the student-only room plugin, (2) send the custom event upon room creation, (3) potentially also send a server ACL event upon room creation (and decide how to implement adding external users later)

- [x] Allow receiving query parameters (for people coming from clicking a Hydrant link, etc)
- [x] Styling, perhaps copy the one from the display name picker, which comes from Wide Tim, which comes from Swolen't Tim, which comes from jt from Discord (sob I need to learn CSS). Or bootstrap/**Bulma**. Idk.

Improvements (ongoing):

- [x] You can go to the chat itself by clicking a button
- [x] The search bar is better and lets you search by partial course number and name (partial, maybe even fuzzy). Also we don't want to reinvent Hydrant since we don't want all the functionality and ideally want to add a "join Matrix" button on Hydrant
- [x] Allow importing from Webathena as well
